apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: triggeriq-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - triggeriq.eu
      secretName: triggeriq-tls # Cert-Manager will create this
  rules:
    - host: triggeriq.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: triggeriq
                port:
                  number: 8081
