apiVersion: v1
kind: Pod
metadata:
  name: s3-reader
  namespace: kube-system
spec:
  serviceAccountName: ebs-csi-controller-sa
  dnsPolicy: 'None'
  dnsConfig:
    nameservers:
      - 172.20.128.94 # CoreDNS service IP
    #      - 8.8.8.8           # Google DNS
    #      - 8.8.4.4           # Google DNS backup
    searches:
      - kube-system.svc.cluster.local
      - svc.cluster.local
      - cluster.local
  containers:
    - name: alpine-tools
      image: alpine:3.15
      command: ['/bin/sh', '-c']
      args:
        - |
          ping -c 3 8.8.8.8;
          nslookup google.com;
          curl https://amazon.com;
          sleep 3600
      tty: true
      stdin: true
      env:
        - name: AWS_REGION
          value: eu-west-3
